name: Менеджер
description: Менеджер по продажам
permissions:
  catalogs:
    Контрагент: [read, write]
    Номенклатура: [read]
    Склад: [read]
    Касса: [read]
    ТипЦен: [read]
    Организация: [read]
    ЕдиницаИзмерения: [read]
    СтавкаНДС: [read]
    НастройкиПользователя: [read]
    ДоговорыКонтрагентов: [read, write]
    СпецификацииНоменклатуры: [read]
    ПодключаемоеОборудование: [read]
  documents:
    Счёт: [read, write]
    РеализацияТоваров: [read, write, post, unpost]
    ПоступлениеТоваров: [read]
    ПриходныйКассовыйОрдер: [read, write, post, unpost]
    УстановкаЦен: [read, write, post, unpost]
    ЗаказПокупателя: [read, write, post, unpost]
    ВозвратОтПокупателя: [read, write, post, unpost]
    ЗакрытиеЗаказовПокупателей: [read, write, post, unpost]
    КорректировкаДолга: [read, write, post, unpost]
  registers:
    Взаиморасчеты: [read]
    ДенежныеСредства: [read]
  reports:
    ОстаткиТоваров: [run]
    ВаловаяПрибыль: [run]
    ПродажиПоКонтрагентам: [run]
    ОплатыРеализаций: [run]
    ЦеныНоменклатуры: [run]
    АктСверки: [run]
    РезервыТоваров: [run]
    СвободныеОстатки: [run]
    ABCАнализПродаж: [run]
    АнализЗаказовПокупателей: [run]
    ПлатежныйКалендарь: [run]
  processors:
    РабочееМестоПродаж: [run]
    ОтгрузкаЗаказов: [run]
    РеализацияИзСчёта: [run]
    ПересчётЦен: [run]
    НастройкаТиповЦен: [run]
    ВыгрузкаВExcel: [run]
    УведомленияПродажи: [run]
    ПечатьЧека: [run]
    ПробитьЧек: [run]
