name: Менеджер
title: Менеджер
titles:
  en: Manager
  de: Manager
  sr: Менаџер
  az: Menecer
  es: Gerente
  fr: Responsable
  hy: Մենեջեր
  ka: მენეჯერი
  kk: Менеджер
  pt: Gerente
  ro: Manager
  tr: Müdür
  uk: Менеджер
  uz: Menejer
  zh: 经理
description: Менеджер по продажам
descriptions:
  en: Sales manager
  de: Vertriebsmitarbeiter
  sr: Менаџер продаје
  az: Satış meneceri
  es: Gerente de ventas
  fr: Responsable commercial
  hy: Վաճառքի մենեջեր
  ka: გაყიდვების მენეჯერი
  kk: Сатылым менеджері
  pt: Gerente de vendas
  ro: Manager de vânzări
  tr: Satış müdürü
  uk: Менеджер з продажу
  uz: Savdo menejeri
  zh: 销售经理
permissions:
  catalogs:
    Контрагент: [read, write]
    Номенклатура: [read]
    Склад: [read]
    Касса: [read]
    ТипЦен: [read]
    Организация: [read]
    ЕдиницаИзмерения: [read]
    СтавкаНДС: [read]
    НастройкиПользователя: [read]
  documents:
    Счёт: [read, write]
    РеализацияТоваров: [read, write, post, unpost]
    ПоступлениеТоваров: [read]
    ПриходныйКассовыйОрдер: [read, write, post, unpost]
    УстановкаЦен: [read, write, post, unpost]
    ЗаказПокупателя: [read, write, post, unpost]
    ВозвратОтПокупателя: [read, write, post, unpost]
  registers:
    Взаиморасчеты: [read]
    ДенежныеСредства: [read]
  reports:
    ОстаткиТоваров: [run]
    ВаловаяПрибыль: [run]
    ПродажиПоКонтрагентам: [run]
    ОплатыРеализаций: [run]
    ЦеныНоменклатуры: [run]
    АктСверки: [run]
    РезервыТоваров: [run]
    СвободныеОстатки: [run]
  processors:
    реализация_из_счёта: [run]
    пересчёт_цен: [run]
    настройка_типов_цен: [run]
    выгрузка_в_excel: [run]
    уведомления_продажи: [run]
