title: Главная — Торговля
layout: rows
rows:
  - widgets:
      - ВыручкаМесяца
      - ВаловаяПрибыльМесяца
      - ПродажиМесяца
  - widgets:
      - ПродажиПоДням
  - widgets:
      - ТопНоменклатуры
      - СтруктураВыручки
  - widgets:
      - БыстрыеДействия
      - ПоследниеДокументы
